### ISSUE TITLE
The pretrained model not work

### ISSUE THREAD

**Issue by robolabsjtu** [koyeongmin/PINet#10]
Hi,
      Firstly, thank you for your sharing code, very nice result. However, when I run the test.py with the pretrained model (640_tensor(0.2298)_lane_detection_network.pkl), always get the same error.I try install pytorch 1.0.1,1.1.0,1.2.0. Please help me, thank you.
#######################
Testing
Get dataset
Get agent
Traceback (most recent call last):
  File "test.py", line 388, in <module>
    Testing()
  File "test.py", line 42, in Testing
    lane_agent.load_weights(640, "tensor(0.2298)")
  File "/home/agv2/Documents/lanes/PINet/agent.py", line 306, in load_weights
    torch.load(self.p.model_path+str(epoch)+'_'+str(loss)+'_'+'lane_detection_network.pkl')
  File "/home/agv2/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 522, in load_state_dict
    .format(name))
KeyError: 'unexpected key "resizing.conv.cbr_unit.1.num_batches_tracked" in state_dict'
###########################

**Comment by koyeongmin** [comment]
Did you change some code of "hourglass_network.py" or "util_hourglass.py"?
In my case, similar errors occur when some codes are changed.

**Comment by robolabsjtu** [comment]
Thank you for reply. No，I do not change any code. Just use the newest version of code.

**Comment by koyeongmin** [comment]
I tested it  by cloning our repository again, but it is working. If it is not working on your system, please try this link, https://discuss.pytorch.org/t/missing-keys-unexpected-keys-in-state-dict-when-loading-self-trained-model/22379/5

**Comment by robolabsjtu** [comment]
Thank you, the link solved my problem. After add a strict=false, the system is ok.
    def load_weights(self, epoch, loss):
        self.lane_detection_network.load_state_dict(
            torch.load(self.p.model_path+str(epoch)+'_'+str(loss)+'_'+'lane_detection_network.pkl'),**False**
        )
