### ISSUE TITLE
What happens if two points exit in the same grid? 

### ISSUE THREAD

**Issue by hlnull** [koyeongmin/PINet#11]
hi, Yeongmin Ko, thanks for your great work.

"In PINet, a grid is matched to 8 or 16 pixels according to the ratio between input size and output size." What happens if two points exit in the same grid? It seems that only one point will be reserved. Will this influence the final result?

Thanks for your reply.

**Comment by koyeongmin** [comment]
Currently, this code can not predict two or more points per one grid. However, in my opinion, it can be improve using other object detection method like YOLO.

**Comment by hlnull** [comment]
Yes, YOLO predicts multiple objects in one grid with anchor boxes. That would be helpful if the lanes contains a large curve.
