### ISSUE TITLE
is it possible to train ten lanes?

### ISSUE THREAD

**Issue by lfxx** [koyeongmin/PINet#3]
Thanks for your execllent work! When i read your source code,i realize that your code can train at most 6 lanes,can i train ten lanes? Do i need to modify net structure?hope for your kindly reply:)@koyeongmin

**Comment by koyeongmin** [comment]
Our network can train on the arbitrary number of lanes. In dataloader, the code use at most 6 lanes, but this is just for improving accuracy on tuSimple dataset. If you do not divide dataset according to the number of lanes, you can train 10 lanes.

**Comment by lfxx** [comment]
thanks!
