### ISSUE TITLE
whether pretrained weights can be provided

### ISSUE THREAD

**Issue by AnRanbel** [koyeongmin/PINet#49]
Hi, I would first want to use your model to evaluate its predictive effect on my custom dataset, and I wonder whether pretrained weights can be provided, thank you.

**Comment by koyeongmin** [comment]
Hi. this link, "https://github.com/koyeongmin/PINet_new", provides the latest models with their pretrained weights on TuSimple, CULane, CurveLane. You can find weights in "savefile" folder. 
Also, the pretrained weights of this repository can be found in "savefile" folder. 
Thank you!

**Comment by AnRanbel** [comment]
> Hi. this link, "https://github.com/koyeongmin/PINet_new", provides the latest models with their pretrained weights on TuSimple, CULane, CurveLane. You can find weights in "savefile" folder. Also, the pretrained weights of this repository can be found in "savefile" folder. Thank you!

Thank you
