### ISSUE TITLE
Missing results

### ISSUE THREAD

**Issue by IntanP** [koyeongmin/PINet#6]
Hi, 

I just tried the codes and everything looks fine, but I don't see the results. 
After running the test.py, I got this:
     Testing
     Get dataset
     Get agent
     Setup GPU mode
     Testing loop
     evaluate
And there isn't any error message. 
What should I do? 

Kind regards, 
Intan

**Comment by koyeongmin** [comment]
If you want to visualize results, you should change mode parameter in "parameters.py". In this repository, default mode is 3, and it means just evaluation.

**Comment by IntanP** [comment]
Thank you for the fast replay! 
I get the results with visualization now. They look really amazing!
