### ISSUE TITLE
Run the test.py in mode 1

### ISSUE THREAD

**Issue by Kimbo-Chang** [koyeongmin/PINet#9]
I run the test.py in mode 1, My video size is (1280,800),but it show video is (512,256).
If I want show the 1280*800 video,what i need modify code ?

**Comment by lfxx** [comment]
No,just run the code:)

**Comment by koyeongmin** [comment]
At line 75("test.py"), ti[0] is a result frame. You can apply a resize function to it.

**Comment by Kimbo-Chang** [comment]
I know that. But ti[0] resize the(1280,800), video will become  blur.
Can I resize the (1280,800), and video will Clearly not blur?

**Comment by koyeongmin** [comment]
Because this process is up-sampling from low resolution, result video can become little blur.
If you want to get a clear video, you can use the original video, and transform points from (512,256) to (1280,800) to get exact points on the lanes.

**Comment by Kimbo-Chang** [comment]
Ok, thanks for you help.
